# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(683, 177)
        MainForm.setStyleSheet("#MainForm{\n"
"    background-color: #fbfcff;\n"
"}\n"
"\n"
"QFrame#topLayout{\n"
"    border: 1px solid dodgerblue;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame#bottomLayout{\n"
"    border: 1px solid orangered;\n"
"    border-radius: 10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QFrame(MainForm)
        self.topLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLayout.setObjectName("topLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.topLayout)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.originalLinkLineEdit = QtWidgets.QLineEdit(self.topLayout)
        self.originalLinkLineEdit.setObjectName("origianlLinkLineEdit")
        self.horizontalLayout.addWidget(self.originalLinkLineEdit)
        self.getLinkButton = QtWidgets.QPushButton(self.topLayout)
        self.getLinkButton.setAutoFillBackground(True)
        self.getLinkButton.setObjectName("getLinkButton")
        self.horizontalLayout.addWidget(self.getLinkButton)
        self.verticalLayout.addWidget(self.topLayout)
        self.bottomLayout = QtWidgets.QFrame(MainForm)
        self.bottomLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLayout.setObjectName("bottomLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomLayout)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.bottomLayout)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nimbahaLineEdit = QtWidgets.QLineEdit(self.bottomLayout)
        self.nimbahaLineEdit.setReadOnly(True)
        self.nimbahaLineEdit.setObjectName("nimbahaLineEdit")
        self.horizontalLayout_2.addWidget(self.nimbahaLineEdit)
        self.copyLinkButton = QtWidgets.QPushButton(self.bottomLayout)
        self.copyLinkButton.setObjectName("copyLinkButton")
        self.horizontalLayout_2.addWidget(self.copyLinkButton)
        self.verticalLayout.addWidget(self.bottomLayout)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Linker"))
        self.label.setText(_translate("MainForm", "لینک فایل"))
        self.getLinkButton.setText(_translate("MainForm", "Get Link"))
        self.label_2.setText(_translate("MainForm", "لینک نیم بها"))
        self.copyLinkButton.setText(_translate("MainForm", "Copy"))
